// generated by stringer -type=Score; DO NOT EDIT

package score

import "fmt"

const _Score_name = "OKLowWarningLowHighWarningHigh"

var _Score_index = [...]uint8{0, 2, 12, 15, 26, 30}

func (i Score) String() string {
	i -= 1
	if i < 0 || i >= Score(len(_Score_index)-1) {
		return fmt.Sprintf("Score(%d)", i+1)
	}
	return _Score_name[_Score_index[i]:_Score_index[i+1]]
}
